apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-demo-preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - list:
        elements:
          - environment: dev
          - environment: prod

  template:
    metadata:
      name: 'gitops-demo-appset-{{.environment}}'
      labels:
        app.kubernetes.io/name: gitops-demo
        poc: applicationset
        environment: '{{.environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/prashantbat/gitops-argocd-lab.git
        targetRevision: main
        path: 'apps/gitops-demo/overlays/appset-{{.environment}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'gitops-demo-appset-{{.environment}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
